### ISSUE TITLE
[BUG] Field that is a reference to another schema doesn't get saved to database

### ISSUE THREAD

**Issue by garyburton** [aesmail/kaffy#118]
**Versions Used**
Kaffy: 0.8.0
Phoenix: 1.5.1
Elixir: 1.10.2

**What's actually happening?**
I am very new to Elixir and Phoenix so this could well be something I am doing wrong. I am creating a simple blog type site with articles and accounts. Articles belong_to account and accounts has_many articles. All this shows up fine in Kaffy and I can create Articles through the admin.

When I create an Article in the admin I get a field called Account which is a dropdown that lists all the accounts (correctly) and I can see the value of the option elements contains the correct account id number but when I select one that account id does not get saved into account_id column in the articles table - it is null. 

These are the schemas I have:
```
schema "articles" do
    field :content, :string
    field :title, :string
    belongs_to :account, MyApp.Accounts.Account

    timestamps()
  end
```
and the "accounts" schema
```
schema "accounts" do
    field :email, :string
    field :password, :string, virtual: true
    field :encrypted_password, :string
    has_many :articles, MyApp.Articles.Article

    timestamps()
end
```
and a migration like so to create the articles table.
```
def change do
    create table(:articles) do
      add :title, :string
      add :content, :string
      add :account_id, references(:accounts, on_delete: :nothing)

      timestamps()
    end

    create index(:articles, [:account_id])
end
```

**What should happen instead?**
I would expect this account Id to be saved and displayed.

**Comment by aesmail** [comment]
Hello @garyburton 

Thanks fo using Kaffy and welcome to the elixir world 🙏🏻

When you create schemas with foreign keys, phoenix by default does not include those fields in the list of "accepted" fields from user parameters. You have to include that yourself.

You probably have a `changeset/2` function in your `Article` schema with something like this:
```elixir
def changeset(article, attrs \\ %{}) do
  article
  |> cast(attrs, [:content, :title])
  |> validate_required([:content, :title])
end
```

Just add `:account_id` to the list of fields to cast:
```elixir
def changeset(article, attrs \\ %{}) do
  article
  |> cast(attrs, [:content, :title, :account_id])
  |> validate_required([:content, :title, :account_id]) # you might also want to make it a required field
end
```

Please note that this is not recommended for production since this allows users to submit any account_id which might not be the desired functionality. You might need to have a special "changeset" function (like `super_changeset/2` for example) that you use with Kaffy.

Take a look at the [changesets section](https://github.com/aesmail/kaffy#changesets) in the README file to have a better understanding of this.

I hope this solves your issue. Please let me know if this is not the case.

**Comment by aesmail** [comment]
Please let me know if this is still not working out for you and I'll reopen the issue.

**Comment by garyburton** [comment]
Sorry for delay getting back to you. That worked perfectly thank you! I thought it was likely something stupid I was doing haha. Thanks again for the help.

**Comment by aesmail** [comment]
You're very welcome.

Actually, it's a good thing you reported this. Thinking about it now, maybe we do need a way to inform the user about this potential issue with associations.
