### ISSUE TITLE
[BUG] Error messages are not handled

### ISSUE THREAD

**Issue by eduardoscottini** [aesmail/kaffy#147]
**Versions Used**
Kaffy: v0.9.0
Phoenix: v1.4.17
Elixir: v1.9

**What's actually happening?**
changeset errors are not properly treated to replace text variables.
The message returned to the user: `List Price Discount Rate must be less than or equal to %{number}!`

**What should happen instead?**
We can deal with this using [traverse_errors/2](https://hexdocs.pm/ecto/Ecto.Changeset.html#traverse_errors/2)

The message that should be returned to the user: `List Price Discount Rate must be less than or equal to 1!`

**Screenshots**
![image](https://user-images.githubusercontent.com/10498125/91862885-e14be480-ec44-11ea-9301-4050e2b0c593.png)

**Comment by eduardoscottini** [comment]
Hi @aesmail! 😃 

I was left with some questions: 
- are the project tests not passing?
![image](https://user-images.githubusercontent.com/10498125/91871983-c0d45800-ec4d-11ea-8c85-7ea050eb03c7.png)
all the failed tests are complaining about the lack of the `Resource` module

- The elixir version in `mix.exs` is on 1.7, but the project doesn't even compile on this version, am I doing something wrong?(> 1.7 works fine)
![image](https://user-images.githubusercontent.com/10498125/91872351-288aa300-ec4e-11ea-9bd2-b8947d460fa3.png)

**Comment by aesmail** [comment]
Hey @eduardoscottini,
The tests are not actually up to date and need major overhaul.
The issue is, Kaffy is undergoing a major rewrite to support some upcoming features. This major rewrite would render almost all current tests as invalid/obsolete.
Having said that, the end goal is to have a compete test suite which covers around 100% of the codebase.

The 1.7 issue is new and shouldn't exist. I'll look into it.
