### ISSUE TITLE
[BUG] Upload file

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#85]
Hi,

Trying to figure out how to upload a file from Kaffy, could you give some insight what should be the best way to achieve that!
I tried with `before_create` callback but it's not working for me.

Here how my upload work from the frontend:
https://github.com/areski/ex-chitchat/blob/master/lib/chit_chat_web/controllers/upload_controller.ex
Here the schema:
https://github.com/areski/ex-chitchat/blob/master/lib/chit_chat/documents/upload.ex
and Kaffy upload admin:
https://github.com/areski/ex-chitchat/blob/master/lib/chit_chat_web/admin/upload_admin.ex

I have the feeling that somehow I should cancel the insert from Kaffy and take the hand but not sure how I should do that?
Have you tried uploading files with Kaffy?

**Comment by aesmail** [comment]
I think since Kaffy is handling the actual database operation, you might need to refactor a few functions you have.
You could use `before_create` but you have to return a changeset and not the `{:ok, upload}` value returned from `Repo.insert`.

In your `Documents.create_upload_from_plug_upload(upload)` function, if you could make this return a changeset and have a different function save that changeset for you in your `create` action, it might work.

Example:

```elixir
# you would have 2 functions instead of the create_upload_from_plug_upload one
def prepare_upload(%Plug.Upload{filename: fn, path: p}) do
  # do some processing
  changeset = Upload.changeset(some_params)
  {:ok, changeset}
end

# you would use this in your own controller, Kaffy doesn't need this.
def save_upload(changeset), do: Repo.insert(changeset)

# Kaffy callbacks
def before_create(conn, changeset) do
  # do some processing with conn, get the upload
  upload = conn.params["upload"]
  prepare_upload(upload)
end
```

Let me know if this still doesn't work for you.

**Comment by aesmail** [comment]
I think this is done with your PR 🙏🏻
