### ISSUE TITLE
[BUG] Do we need before_save & after_save ?

### ISSUE THREAD

**Issue by areski** [aesmail/kaffy#92]
```doc
    before_create/2
    before_save/2
    inserting the record happens here: Repo.insert/1
    after_save/2
    after_create/2
```
Is it really useful to have `before_save` & `after_save`, I cannot see in which situation this would be needed, as we can put what we need in `before_create`.
I see that `before_save` is use on both update and insert, but still I don't see the use-case for this, could you shed some light?

My view is that if it's redundant it might be best to not have them.

**Comment by aesmail** [comment]
When it purely comes to callbacks, I think `before_save` and `after_save` are useful when you need to do something no matter whether the record is new or existing. They are just a shortcut for implementing both `*_insert` and `*_update`.

For example, you want to send an email to the admins whenever the "status" of a post is "needs_review". You might create a new post with the "needs_review" status already selected, or maybe later after the post is published, you change the status to "needs_review" in which case you want to send an email to the admins.

Without `after_save`, you would have to implement both `after_insert` and `after_update` with the same logic.

Here is a link to [rails callbacks](https://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks) and [django signals](https://docs.djangoproject.com/en/3.0/topics/signals/) to maybe provide detailed descriptions. I feel the ones we have now are more than enough, especially since ecto differs from rails/django models and how they validate and insert values into the database.

**Comment by aesmail** [comment]
I'm interested to know your point of view since you've never used rails so you're not influenced by it as much as I am.

**Comment by areski** [comment]
I now that this is a nice-to-have shortcut and in some cases it's a handy thing to use rather than having to write 2 callbacks functions, but sometime I also feel that simplicity is a feature of his own (especially for faced APIs to other developer).

I don't have a strong opinion about this, so I'm like 50/50.

I'm sorry this will have to be your call :)

**Comment by aesmail** [comment]
It's very interesting when you describe things coming from a different background!

I actually lean towards keeping it, so it's going to stay. Also, since a lot of phoenix developers came from the rails world, I think it might be a welcome addition, albeit only in Kaffy and not phoenix.

This, however, makes me think that it needs a special description in the docs to explain it fully and clearly.

I almost went as far as having a visual "indication" in the resource form page that "this resource has defined callbacks" or something like this 🤔😅

**Comment by areski** [comment]
Valid point! 
I'm closing this issue, one less :)
